[project]
name = "lisenare"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.4",
    "boto3>=1.43.18",
    "en-core-web-sm",
    "fakeredis>=2.35.1",
    "fastapi[standard]>=0.120.1",
    "fastdtw>=0.3.4",
    "ffmpeg-python>=0.2.0",
    "fsrs>=6.3.0",
    "google-cloud-storage>=3.10.1",
    "google-genai>=1.71.0",
    "httpx>=0.28.1",
    "jiwer>=4.0.0",
    "kokoro>=0.9.4",
    "langchain-ollama>=1.0.1",
    "langchain-postgres>=0.0.17",
    "librosa>=0.11.0",
    "mutagen>=1.47.0",
    "numpy>=2.3.4",
    "ollama>=0.6.1",
    "openpyxl>=3.1.5",
    "phonemizer>=3.3.0",
    "pip>=25.3",
    "psycopg2-binary>=2.9.12",
    "pwdlib[argon2]>=0.3.0",
    "pydantic-settings>=2.11.0",
    "pyenchant>=3.3.0",
    "pyjwt>=2.10.1",
    "pytest>=9.0.2",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.20",
    "redis>=7.1.0",
    "seaborn>=0.13.2",
    "sentence-transformers>=5.1.2",
    "soundfile>=0.13.1",
    "spacy>=3.8.9",
    "sqlmodel>=0.0.27",
    "textstat>=0.7.12",
    "torchaudio==2.9",
    "torchcodec==0.9",
    "wordfreq>=3.1.1",
    "youtube-transcript-api>=1.2.3",
    "yt-dlp>=2025.11.12",
    "yt-dlp-ejs>=0.3.1",
]

[tool.ruff]
line-length = 79

[tool.uv.sources]
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl" }
