[project]
name = "lisenare"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.3.5",
    "fastapi[standard]>=0.120.1",
    "ffmpeg-python>=0.2.0",
    "jupyter>=1.1.1",
    "librosa>=0.11.0",
    "llama-cpp-python>=0.3.16",
    "numpy>=2.3.4",
    "openpyxl>=3.1.5",
    "pip>=25.3",
    "pwdlib[argon2]>=0.3.0",
    "pydantic-settings>=2.11.0",
    "pyjwt>=2.10.1",
    "python-multipart>=0.0.20",
    "redis>=7.1.0",
    "seaborn>=0.13.2",
    "sentence-transformers>=5.1.2",
    "spacy>=3.8.9",
    "sqlmodel>=0.0.27",
    "stable-baselines3[extra]>=2.7.0",
    "youtube-transcript-api>=1.2.3",
    "yt-dlp>=2025.11.12",
    "yt-dlp-ejs>=0.3.1",
]
