"""add snippetreaction and remove snippetlike

Revision ID: 7ad70066c218
Revises:
Create Date: 2026-05-05 18:54:56.709019

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ad70066c218"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "snippetreaction",
        sa.Column("learner_id", sa.Integer(), nullable=False),
        sa.Column("snippet_id", sa.Integer(), nullable=False),
        sa.Column("reaction", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snippet_id"],
            ["snippet.id"],
        ),
        sa.PrimaryKeyConstraint("learner_id", "snippet_id"),
    )
    op.drop_table("snippetlike")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_brick_search", table_name="brick", postgresql_using="gin"
    )
    op.create_index(
        op.f("idx_brick_search"),
        "brick",
        [
            sa.literal_column(
                "to_tsvector('simple'::regconfig, (target_text::text || ' '::text) || native_text::text)"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "langchain_pg_collection",
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "cmetadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint(
            "uuid", name=op.f("langchain_pg_collection_pkey")
        ),
        sa.UniqueConstraint(
            "name",
            name=op.f("langchain_pg_collection_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "snippetlike",
        sa.Column(
            "learner_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "snippet_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner.id"],
            name=op.f("snippetlike_learner_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["snippet_id"],
            ["snippet.id"],
            name=op.f("snippetlike_snippet_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "learner_id", "snippet_id", name=op.f("snippetlike_pkey")
        ),
    )
    op.create_table(
        "langchain_pg_embedding",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "collection_id", sa.UUID(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "embedding", sa.NullType(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "document", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "cmetadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["langchain_pg_collection.uuid"],
            name=op.f("langchain_pg_embedding_collection_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("langchain_pg_embedding_pkey")
        ),
    )
    op.create_index(
        op.f("ix_cmetadata_gin"),
        "langchain_pg_embedding",
        ["cmetadata"],
        unique=False,
        postgresql_ops={"cmetadata": "jsonb_path_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_langchain_hnsw"),
        "langchain_pg_embedding",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="hnsw",
    )
    op.drop_table("snippetreaction")
    # ### end Alembic commands ###
