"""add review log column and learner setting for personal optmization

Revision ID: 7d632635e8cb
Revises: f310dc922ba3
Create Date: 2026-05-12 09:52:57.929725

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d632635e8cb"
down_revision: Union[str, Sequence[str], None] = "f310dc922ba3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learnersetting",
        sa.Column("learner_id", sa.Integer(), nullable=False),
        sa.Column(
            "fsrs_weights",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("target_retention", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner.id"],
        ),
        sa.PrimaryKeyConstraint("learner_id"),
    )

    # add column as NULLABLE first
    op.add_column(
        "review",
        sa.Column(
            "fsrs_log_dict",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,  # Change this to True temporary
        ),
    )

    # fills existing rows so we can make it NOT NULL in the next step
    op.execute(
        "UPDATE review SET fsrs_log_dict = '{}'::jsonb WHERE fsrs_log_dict IS NULL"
    )

    op.alter_column("review", "fsrs_log_dict", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review", "fsrs_log_dict")
    op.drop_index(
        "idx_brick_search", table_name="brick", postgresql_using="gin"
    )
    op.create_index(
        op.f("idx_brick_search"),
        "brick",
        [
            sa.literal_column(
                "to_tsvector('simple'::regconfig, (target_text::text || ' '::text) || native_text::text)"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "langchain_pg_embedding",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "collection_id", sa.UUID(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "embedding", sa.NullType(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "document", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "cmetadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["langchain_pg_collection.uuid"],
            name=op.f("langchain_pg_embedding_collection_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("langchain_pg_embedding_pkey")
        ),
    )
    op.create_index(
        op.f("ix_cmetadata_gin"),
        "langchain_pg_embedding",
        ["cmetadata"],
        unique=False,
        postgresql_ops={"cmetadata": "jsonb_path_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_langchain_hnsw"),
        "langchain_pg_embedding",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="hnsw",
    )
    op.create_table(
        "langchain_pg_collection",
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "cmetadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint(
            "uuid", name=op.f("langchain_pg_collection_pkey")
        ),
        sa.UniqueConstraint(
            "name",
            name=op.f("langchain_pg_collection_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("learnersetting")
    # ### end Alembic commands ###
