"""recreate interactiontype

Revision ID: 90c7f6ffa6d8
Revises: 7ad70066c218
Create Date: 2026-05-05 22:32:28.774229

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90c7f6ffa6d8"
down_revision: Union[str, Sequence[str], None] = "7ad70066c218"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "snippetinteraction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("snippet_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "LISTEN",
                "LIKE",
                "DISLIKE",
                "REMOVE_REACTION",
                "ADD",
                "TIME_SPENT",
                name="interactiontype",
            ),
            nullable=False,
        ),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("learner_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "\n            (type = 'TIME_SPENT' AND duration IS NOT NULL)\n            OR\n            (type != 'TIME_SPENT' AND duration IS NULL)\n            ",
            name="check_duration_consistency",
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snippet_id"],
            ["snippet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_brick_search", table_name="brick", postgresql_using="gin"
    )
    op.create_index(
        op.f("idx_brick_search"),
        "brick",
        [
            sa.literal_column(
                "to_tsvector('simple'::regconfig, (target_text::text || ' '::text) || native_text::text)"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "langchain_pg_collection",
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "cmetadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint(
            "uuid", name=op.f("langchain_pg_collection_pkey")
        ),
        sa.UniqueConstraint(
            "name",
            name=op.f("langchain_pg_collection_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "langchain_pg_embedding",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "collection_id", sa.UUID(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "embedding", sa.NullType(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "document", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "cmetadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["langchain_pg_collection.uuid"],
            name=op.f("langchain_pg_embedding_collection_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("langchain_pg_embedding_pkey")
        ),
    )
    op.create_index(
        op.f("ix_cmetadata_gin"),
        "langchain_pg_embedding",
        ["cmetadata"],
        unique=False,
        postgresql_ops={"cmetadata": "jsonb_path_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_langchain_hnsw"),
        "langchain_pg_embedding",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="hnsw",
    )
    op.drop_table("snippetinteraction")
    # ### end Alembic commands ###
