"""upgrade broken brick report table

Revision ID: b2129000e41d
Revises: 7d632635e8cb
Create Date: 2026-05-13 10:53:21.120478

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2129000e41d"
down_revision: Union[str, Sequence[str], None] = "7d632635e8cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("brokenbrickreport")
    op.create_table(
        "brokenbrickreport",
        sa.Column(
            "learner_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "brick_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "reported_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learner.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["brick_id"],
            ["brick.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "learner_id",
            "brick_id",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "brokenbrickreport",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "brokenbrickreport",
        sa.Column(
            "filename", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "brokenbrickreport", type_="foreignkey")
    op.drop_constraint(None, "brokenbrickreport", type_="foreignkey")
    op.create_index(
        op.f("ix_brokenbrickreport_filename"),
        "brokenbrickreport",
        ["filename"],
        unique=True,
    )
    op.drop_column("brokenbrickreport", "brick_id")
    op.drop_column("brokenbrickreport", "learner_id")
    op.drop_index(
        "idx_brick_search", table_name="brick", postgresql_using="gin"
    )
    op.create_index(
        op.f("idx_brick_search"),
        "brick",
        [
            sa.literal_column(
                "to_tsvector('simple'::regconfig, (target_text::text || ' '::text) || native_text::text)"
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "langchain_pg_collection",
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "cmetadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint(
            "uuid", name=op.f("langchain_pg_collection_pkey")
        ),
        sa.UniqueConstraint(
            "name",
            name=op.f("langchain_pg_collection_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "langchain_pg_embedding",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "collection_id", sa.UUID(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "embedding", sa.NullType(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "document", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "cmetadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["langchain_pg_collection.uuid"],
            name=op.f("langchain_pg_embedding_collection_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("langchain_pg_embedding_pkey")
        ),
    )
    op.create_index(
        op.f("ix_cmetadata_gin"),
        "langchain_pg_embedding",
        ["cmetadata"],
        unique=False,
        postgresql_ops={"cmetadata": "jsonb_path_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_langchain_hnsw"),
        "langchain_pg_embedding",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="hnsw",
    )
    # ### end Alembic commands ###
