"""Hằng số cấu hình cho RLM engine (vendor + rút gọn từ project RLM)."""

ROOT_MODEL = "gemini-2.5-flash"
SUB_MODEL = "gemini-2.5-flash"

MAX_ITERATIONS = 8
MAX_STDOUT_CHARS = 2000
MAX_CODE_EXEC_SECONDS = 20
SUB_LM_CONTEXT_CHAR_HINT = 100_000

MAX_RECURSION_DEPTH = 2
DEFAULT_DEPTH = 1

MAX_LLM_OUTPUT_TOKENS = 4096
LLM_RETRY_ATTEMPTS = 3
LLM_RETRY_BACKOFF_SECONDS = 2.0

TRAJECTORY_LOGGING_ENABLED = True
LOG_DIR = "logs/rlm"
